const SET_DAILY_STATS = 'SET_DAILY_STATS';
const GET_DAILY_STATS = 'GET_DAILY_STATS';
const SET_HOURLY_STATS = 'SET_HOURLY_STATS';
const GET_HOURLY_STATS = 'GET_HOURLY_STATS';
const SET_DAILY_EVENTS = 'SET_DAILY_EVENTS';
const GET_DAILY_EVENTS = 'GET_DAILY_EVENTS';
const SET_HOURLY_EVENTS = 'SET_HOURLY_EVENTS';
const GET_HOURLY_EVENTS = 'GET_HOURLY_EVENTS';
const SET_POI = 'SET_POI';
const GET_POI = 'GET_POI';

export default {
    SET_DAILY_EVENTS,
    GET_DAILY_EVENTS,
    SET_DAILY_STATS,
    GET_DAILY_STATS,
    SET_HOURLY_EVENTS,
    GET_HOURLY_EVENTS,
    SET_HOURLY_STATS,
    GET_HOURLY_STATS,
    SET_POI,
    GET_POI
}